# Generated by Django 5.1.2 on 2025-11-30 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_email_verified_customer_phone_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.BooleanField(default=True, editable=False, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for email header. Will be resized to max 400px width.', null=True, upload_to='email_branding/')),
                ('logo_width', models.PositiveIntegerField(default=200, help_text='Logo display width in pixels (max 400px)')),
                ('primary_color', models.CharField(default='#2C5282', help_text='Primary brand color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#4299E1', help_text='Secondary accent color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('success_color', models.CharField(default='#38A169', help_text='Success/approval color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('danger_color', models.CharField(default='#E53E3E', help_text='Danger/error color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#2D3748', help_text='Main text color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(default='#F7FAFC', help_text='Email background color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2C5282)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('company_name', models.CharField(default='RS Systems', help_text='Company name displayed in email footer', max_length=200)),
                ('company_address', models.TextField(blank=True, help_text='Company address (optional, displayed in footer)')),
                ('support_email', models.EmailField(blank=True, help_text='Support email address (optional, displayed in footer)', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number (optional, displayed in footer)', max_length=20)),
                ('website_url', models.URLField(blank=True, help_text='Company website URL (optional)')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL (optional)')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL (optional)')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn company page URL (optional)')),
                ('heading_font', models.CharField(default='Arial, Helvetica, sans-serif', help_text='Font family for headings', max_length=100)),
                ('body_font', models.CharField(default='Arial, Helvetica, sans-serif', help_text='Font family for body text', max_length=100)),
                ('button_border_radius', models.PositiveIntegerField(default=4, help_text='Button border radius in pixels')),
                ('footer_text', models.TextField(blank=True, default='You are receiving this email because you are registered with RS Systems.', help_text='Custom footer text (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated branding configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_branding_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Branding Configuration',
                'verbose_name_plural': 'Email Branding Configuration',
            },
        ),
    ]
