# Generated by Django for notification system performance optimization
# Phase 6: Production Readiness - Database Query Optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailbrandingconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        # Add composite index for common notification queries
        # This index optimizes:
        # 1. Notification history view (filter by recipient_type + recipient_id + read status)
        # 2. Unread count queries (count notifications by recipient + read=False)
        # 3. Daily digest queries (recipient + read + date range)
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient_type', 'recipient_id', 'read', '-created_at'],
                name='notif_recipient_read_created_idx'
            ),
        ),
        # Add index for category filtering (used in notification history filters)
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['category', '-created_at'],
                name='notif_category_created_idx'
            ),
        ),
        # Add index for scheduled notifications (used by send_scheduled_notifications task)
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['scheduled_for'],
                name='notif_scheduled_for_idx',
                condition=models.Q(scheduled_for__isnull=False)
            ),
        ),
        # Add index for notification delivery logs (common queries by notification + channel)
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(
                fields=['notification', 'channel', 'status'],
                name='notif_delivery_log_idx'
            ),
        ),
        # Add index for pending retry queries (used by retry_failed_notifications task)
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(
                fields=['status', 'next_retry_at'],
                name='notif_delivery_retry_idx',
                condition=models.Q(status='pending_retry')
            ),
        ),
    ]
