# Generated by Django 5.1.2 on 2025-09-26 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('portal', models.CharField(choices=[('customer', 'Customer Portal'), ('technician', 'Technician Portal'), ('admin', 'Admin Portal')], default='customer', max_length=20)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='security_lo_usernam_140da1_idx'), models.Index(fields=['ip_address', 'timestamp'], name='security_lo_ip_addr_7bfc42_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('password_changed', 'Password Changed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('data_export', 'Data Exported'), ('settings_changed', 'Settings Changed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_se_event_t_381556_idx'), models.Index(fields=['user', 'timestamp'], name='security_se_user_id_2cad42_idx')],
            },
        ),
    ]
