# Generated by Django 5.1.2 on 2025-04-03 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardoption',
            options={'ordering': ['points_required']},
        ),
        migrations.AlterModelOptions(
            name='rewardredemption',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rewardoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardoption',
            name='points_required',
            field=models.PositiveIntegerField(),
        ),
    ]
