# Generated by Django 5.1.2 on 2025-04-04 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_referrals', '0002_alter_rewardoption_options_and_more'),
        ('technician_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardredemption',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_redemptions', to='technician_portal.technician'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
