# Generated by Django 5.1.1 on 2024-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='expertise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
