# Generated by Django 5.1.2 on 2025-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0005_alter_repair_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='cost_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual price override (overrides automatic pricing)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for price override (required when using custom price)'),
        ),
    ]
