# Generated by Django 5.1.2 on 2025-09-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0006_add_price_override_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Technician', 'verbose_name_plural': 'Technicians'},
        ),
        migrations.AddField(
            model_name='technician',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum repair amount this manager can approve', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='average_repair_time',
            field=models.DurationField(blank=True, help_text='Average time to complete a repair', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='can_assign_work',
            field=models.BooleanField(default=False, help_text='Can assign repairs to other technicians'),
        ),
        migrations.AddField(
            model_name='technician',
            name='can_override_pricing',
            field=models.BooleanField(default=False, help_text='Can override automatic pricing calculations'),
        ),
        migrations.AddField(
            model_name='technician',
            name='customer_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average customer rating (1.00-5.00)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this technician currently active/available?'),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Can this technician perform manager functions?'),
        ),
        migrations.AddField(
            model_name='technician',
            name='managed_technicians',
            field=models.ManyToManyField(blank=True, help_text='Technicians managed by this manager', related_name='managers', to='technician_portal.technician'),
        ),
        migrations.AddField(
            model_name='technician',
            name='repairs_completed',
            field=models.IntegerField(default=0, help_text='Total number of repairs completed'),
        ),
        migrations.AddField(
            model_name='technician',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Working hours schedule (JSON format)'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
