# Generated by Django 5.1.2 on 2025-11-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0013_techniciannotification_repair_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='break_number',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Break number within this batch (1, 2, 3, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='total_breaks_in_batch',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Total number of breaks in this repair batch', null=True),
        ),
    ]
