# Generated by Django 5.1.2 on 2025-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0014_fix_break_number_null_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViscosityRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this rule (e.g., 'Cold Weather', 'Standard Conditions')", max_length=100)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Minimum temperature in °F (leave blank for no minimum)', max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum temperature in °F (leave blank for no maximum)', max_digits=5, null=True)),
                ('recommended_viscosity', models.CharField(help_text="Recommended viscosity level (e.g., 'Low', 'Medium', 'High')", max_length=50)),
                ('suggestion_text', models.TextField(help_text="The suggestion message shown to technicians (e.g., 'Low viscosity recommended for cold conditions')")),
                ('badge_color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='green', help_text='Color of the badge displayed with the suggestion', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which rules are evaluated (lower = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viscosity Recommendation',
                'verbose_name_plural': 'Viscosity Recommendations',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
