# Generated by Django 5.1.2 on 2025-11-29 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_portal', '0016_repair_is_multi_break_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email address has been verified'),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number in E.164 format (e.g., +12025551234)', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
