# Generated by Django 5.1.2 on 2025-09-28 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_options'),
        ('customer_portal', '0002_repairapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_custom_pricing', models.BooleanField(default=False, help_text='Enable custom pricing for this customer')),
                ('repair_1_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for first repair (default: $50)', max_digits=10, null=True)),
                ('repair_2_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for second repair (default: $40)', max_digits=10, null=True)),
                ('repair_3_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for third repair (default: $35)', max_digits=10, null=True)),
                ('repair_4_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for fourth repair (default: $30)', max_digits=10, null=True)),
                ('repair_5_plus_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for fifth+ repairs (default: $25)', max_digits=10, null=True)),
                ('volume_discount_threshold', models.IntegerField(default=10, help_text='Number of repairs needed to qualify for volume discount')),
                ('volume_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 10.00 for 10%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this pricing arrangement')),
                ('created_by', models.ForeignKey(help_text='User who created this pricing configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Pricing',
                'verbose_name_plural': 'Customer Pricing',
                'ordering': ['customer__name'],
            },
        ),
    ]
