# Generated by Django 5.1.2 on 2025-10-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_options'),
        ('customer_portal', '0003_customerpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRepairPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_repair_approval_mode', models.CharField(choices=[('AUTO_APPROVE', 'Auto-approve all field repairs'), ('REQUIRE_APPROVAL', 'Require approval for all field repairs'), ('UNIT_THRESHOLD', 'Auto-approve up to unit threshold per visit')], default='REQUIRE_APPROVAL', help_text='How should field-discovered repairs be handled?', max_length=20)),
                ('units_per_visit_threshold', models.IntegerField(default=5, help_text='Max number of units technician can repair per visit without approval (only applies in Unit Threshold mode)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_preferences', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Repair Preference',
                'verbose_name_plural': 'Customer Repair Preferences',
            },
        ),
    ]
