# Generated by Django 5.1.2 on 2025-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_customerrepairpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrepairpreference',
            name='lot_walking_days',
            field=models.JSONField(blank=True, default=list, help_text='Preferred days of week for lot walking (stored as list)'),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='lot_walking_enabled',
            field=models.BooleanField(default=False, help_text='Enable scheduled lot walking service for this customer'),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='lot_walking_frequency',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly (Every 2 weeks)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (Every 3 months)')], default='WEEKLY', help_text='How often should technicians walk your lot?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerrepairpreference',
            name='lot_walking_time',
            field=models.TimeField(blank=True, help_text='Preferred time for lot walking (e.g., 9:00 AM)', null=True),
        ),
    ]
