# Generated by Django 5.1.2 on 2025-10-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_customerrepairpreference_lot_walking_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepairpreference',
            name='units_per_visit_threshold',
            field=models.IntegerField(blank=True, default=5, help_text='Max number of units technician can repair per visit without approval (only applies in Unit Threshold mode)', null=True),
        ),
    ]
