# Generated by Django 5.1.2 on 2025-03-05 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, null=True, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=246, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
            ],
        ),
    ]
